[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/"
  to = "https://sohantalukder.github.io/"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "https://sohantalukder.github.io/"
  status = 301
  force = true
